import race_status from "./race_status.json";

const WEAPON_CHARACTOR_PARTS: string[] = ["左手", "右手"];
const AMMUNITION_CHARACTOR_PARTS: string[] = ["矢/弾"];
const ARMOR_CHARACTOR_PARTS: string[] = ["頭(防)", "胴(防)", "手(防)", "パンツ(防)", "靴(防)", "肩(防)", "腰(防)"];
const ORNAMENT_CHARACTOR_PARTS: string[] = ["頭(装)", "顔(装)", "耳(装)", "指(装)", "胸(装)", "腰(装)", "背中(装)"];
const EQUIP_CHARACTOR_PARTS: string[] = WEAPON_CHARACTOR_PARTS.concat(AMMUNITION_CHARACTOR_PARTS, ARMOR_CHARACTOR_PARTS, ORNAMENT_CHARACTOR_PARTS);

interface CONFIGS {
  API_URL: string;
  SKILL_NAMES: string[];
  BATTLE_SKILL_NAMES: string[];
  EXPERIENCE_SKILL_NAMES: string[];
  BASIC_SKILL_NAMES: string[];
  PRODUCT_SKILL_NAMES: string[];
  ATTACK_SKILL_NAMES: string[];
  SPELL_NAMES: string[];
  RACE_STATUS: { [key: string]: { [key: string]: { [key: string]: number } } };
  RACES: string[];
  RACE_CONVERT_NAME: { [race_key: string]: string };
  STATUS_COEFFICIENTS: { [key: string]: number };

  WEAPON_EQUIP_PARTS: string[];
  AMMUNITION_EQUIP_PARTS: string[];
  ARMOR_EQUIP_PARTS: string[];
  ORNAMENT_EQUIP_PARTS: string[];

  WEAPON_CHARACTOR_PARTS: string[];
  AMMUNITION_CHARACTOR_PARTS: string[];
  ARMOR_CHARACTOR_PARTS: string[];
  ORNAMENT_CHARACTOR_PARTS: string[];
  EQUIP_CHARACTOR_PARTS: string[];

  INCREAS_ADD_NAMES: string[];
  INCREAS_RATIO_NAMES: string[];

  REDUCE_NAMES: string[];
  REDUCE_ADDITIONAL_NAMES: string[];
  REDUCE_MAX_NAMES: string[];
  PRODUCT_DATA_KEYS: string[];
  SIMPLE_EQUIP_TYPE: string[];
  REGENERATE: { [key: string]: { [key: string]: { [key: string]: number } } };
  STATUS_CAP: { [key: string]: number };
  DEFAULT_TABLE_ROW_LIMIT: number;
  EQUIP_TABLE_COLUMNS: { [key: string]: string }[];
  DEFAULT_EQUIP_TABLE_COLUMN_NAMES: String[];
  SKILL_CONVERT: { [key: string]: string };
  SKILLNAME_CONVERT_IMPORT: { [skill_name: string]: string };
  BUFF_DATA_TYPES: string[];
  ABBREVIATE_SKILL_NAME: { [skill_name: string]: string };
}

let configs: CONFIGS = {
  // API_URL: `http://localhost:8080`,
  API_URL: "https://asia-northeast1-moe-status.cloudfunctions.net/get",

  SKILL_NAMES: [
    "筋力",
    "着こなし",
    "攻撃回避",
    "生命力",
    "知能",
    "持久力",
    "精神力",
    "集中力",
    "呪文抵抗力",
    "戦闘技術",
    "魔法熟練",
    "盾",
    "刀剣",
    "こんぼう",
    "槍",
    "銃器",
    "投げ",
    "弓",
    "酩酊",
    "暗黒命令",
    "牙",
    "自然調和",
    "調教",
    "罠",
    "取引",
    "物まね",
    "素手",
    "キック",
    "ダンス",
    "パフォーマンス",
    "盗み",
    "音楽",
    "シャウト",
    "ギャンブル",
    "破壊魔法",
    "回復魔法",
    "強化魔法",
    "神秘魔法",
    "召喚魔法",
    "死の魔法",
    "落下耐性",
    "水泳",
    "死体回収",
    "包帯",
    "自然回復",
    "採掘",
    "伐採",
    "収穫",
    "釣り",
    "解読",
    "料理",
    "醸造",
    "鍛冶",
    "木工",
    "裁縫",
    "装飾細工",
    "複製",
    "薬調合",
    "美容",
    "栽培",
  ],
  BATTLE_SKILL_NAMES: ["筋力", "着こなし", "攻撃回避", "生命力", "知能", "持久力", "精神力", "集中力", "呪文抵抗力"],
  EXPERIENCE_SKILL_NAMES: [
    "戦闘技術",
    "魔法熟練",
    "盾",
    "刀剣",
    "こんぼう",
    "槍",
    "銃器",
    "投げ",
    "弓",
    "酩酊",
    "暗黒命令",
    "牙",
    "自然調和",
    "調教",
    "罠",
    "取引",
    "物まね",
    "素手",
    "キック",
    "ダンス",
    "パフォーマンス",
    "盗み",
    "音楽",
    "シャウト",
    "ギャンブル",
    "破壊魔法",
    "回復魔法",
    "強化魔法",
    "神秘魔法",
    "召喚魔法",
    "死の魔法",
  ],
  BASIC_SKILL_NAMES: ["落下耐性", "水泳", "死体回収", "包帯", "自然回復", "採掘", "伐採", "収穫", "釣り", "解読"],
  PRODUCT_SKILL_NAMES: ["料理", "醸造", "鍛冶", "木工", "裁縫", "装飾細工", "複製", "薬調合", "美容", "栽培"],
  ATTACK_SKILL_NAMES: ["刀剣", "こんぼう", "槍", "銃器", "弓", "素手"],
  SPELL_NAMES: ["破壊魔法", "回復魔法", "強化魔法", "神秘魔法", "召喚魔法", "死の魔法"],

  RACE_STATUS: race_status,
  RACES: Object.keys(race_status),
  RACE_CONVERT_NAME: { newter: "ニューター", cognite: "コグニート", elmony: "エルモニー", pandemos: "パンデモス" },
  STATUS_COEFFICIENTS: { HP: 3, MP: 3, ST: 3, 攻撃力: 0.2, 命中: 1, 防御力: 0.2, 回避: 1, 魔力: 1, 呪文抵抗力: 1, 重量: 1.5 },

  WEAPON_EQUIP_PARTS: ["左(1)", "左(2)", "右(1)", "右(2)", "右左(1)", "矢/弾"],
  AMMUNITION_EQUIP_PARTS: ["矢/弾"],
  ARMOR_EQUIP_PARTS: ["頭(防)", "胴(防)", "手(防)", "パンツ(防)", "靴(防)", "肩(防)", "腰(防)"],
  ORNAMENT_EQUIP_PARTS: ["頭(装)", "顔(装)", "耳(装)", "指(装)", "胸(装)", "腰(装)", "背中(装)"],

  WEAPON_CHARACTOR_PARTS: WEAPON_CHARACTOR_PARTS,
  AMMUNITION_CHARACTOR_PARTS: AMMUNITION_CHARACTOR_PARTS,
  ARMOR_CHARACTOR_PARTS: ARMOR_CHARACTOR_PARTS,
  ORNAMENT_CHARACTOR_PARTS: ORNAMENT_CHARACTOR_PARTS,
  EQUIP_CHARACTOR_PARTS: EQUIP_CHARACTOR_PARTS,

  REDUCE_NAMES: [
    "物理ダメージ",
    "魔法ダメージ",
    "ST消費",
    "MP消費",
    "落下ダメージ",
    "落下速度",
    "所持重量",
    "潤喉度",
    "満腹度",
    "潤喉度軽減",
    "アイテム使用速度",
  ],
  REDUCE_ADDITIONAL_NAMES: ["ST消費", "MP消費", "落下ダメージ"],
  REDUCE_MAX_NAMES: ["物理ダメージ", "魔法ダメージ"],

  INCREAS_ADD_NAMES: [
    "銃器射程",
    "投擲射程",
    "音楽範囲",
    "魔法射程",
    "攻撃範囲",
    "シャウト範囲",
    "キック攻撃力補正",
    "キック命中率補正",
    "採掘命中率",
    "牙攻撃力補正",
    "牙命中率補正",
    "攻撃力依存ダメージ",
    "スキル上昇率",
    "ペット経験値",
    "サイズ変更",
    "沈む速度",
    "料理ヒットゾーン",
    "料理グレードゾーン",
    "料理ゲージ滑り",
    "料理ゲージ速度",
    "醸造ヒットゾーン",
    "醸造グレードゾーン",
    "醸造ゲージ滑り",
    "醸造ゲージ速度",
    "鍛冶ヒットゾーン",
    "鍛冶グレードゾーン",
    "鍛冶ゲージ滑り",
    "鍛冶ゲージ速度",
    "木工ヒットゾーン",
    "木工グレードゾーン",
    "木工ゲージ滑り",
    "木工ゲージ速度",
    "複製ヒットゾーン",
    "複製グレードゾーン",
    "複製ゲージ滑り",
    "複製ゲージ速度",
    "裁縫ヒットゾーン",
    "裁縫グレードゾーン",
    "裁縫ゲージ滑り",
    "裁縫ゲージ速度",
    "装飾細工ヒットゾーン",
    "装飾細工グレードゾーン",
    "装飾細工ゲージ滑り",
    "装飾細工ゲージ速度",
    "薬調合ヒットゾーン",
    "薬調合グレードゾーン",
    "薬調合ゲージ滑り",
    "薬調合ゲージ速度",
    "美容ヒットゾーン",
    "美容グレードゾーン",
    "美容ゲージ滑り",
    "美容ゲージ速度",
    "ミスリル強化ヒットゾーン",
    "ミスリル強化滑り",
    "ミスリル強化ゲージ速度",
    "全ヒットゾーン",
    "全グレードゾーン",
    "全ゲージ滑り",
    "全ゲージ速度",
  ],
  INCREAS_RATIO_NAMES: ["盗み成功率", "包帯回復量", "罠回避率上昇", "詠唱妨害耐性", "クリティカル率"],
  PRODUCT_DATA_KEYS: [
    "料理ヒットゾーン",
    "料理グレードゾーン",
    "料理ゲージ滑り",
    "料理ゲージ速度",
    "醸造ヒットゾーン",
    "醸造グレードゾーン",
    "醸造ゲージ滑り",
    "醸造ゲージ速度",
    "鍛冶ヒットゾーン",
    "鍛冶グレードゾーン",
    "鍛冶ゲージ滑り",
    "鍛冶ゲージ速度",
    "木工ヒットゾーン",
    "木工グレードゾーン",
    "木工ゲージ滑り",
    "木工ゲージ速度",
    "複製ヒットゾーン",
    "複製グレードゾーン",
    "複製ゲージ滑り",
    "複製ゲージ速度",
    "裁縫ヒットゾーン",
    "裁縫グレードゾーン",
    "裁縫ゲージ滑り",
    "裁縫ゲージ速度",
    "装飾細工ヒットゾーン",
    "装飾細工グレードゾーン",
    "装飾細工ゲージ滑り",
    "装飾細工ゲージ速度",
    "薬調合ヒットゾーン",
    "薬調合グレードゾーン",
    "薬調合ゲージ滑り",
    "薬調合ゲージ速度",
    "美容ヒットゾーン",
    "美容グレードゾーン",
    "美容ゲージ滑り",
    "美容ゲージ速度",
    "ミスリル強化ヒットゾーン",
    "ミスリル強化滑り",
    "ミスリル強化ゲージ速度",
    "全ヒットゾーン",
    "全グレードゾーン",
    "全ゲージ滑り",
    "全ゲージ速度",
  ],
  // CONVERT_PARTS:{"右(1)":["右手"], "右(2)":"右手", "左(1)":["右手"], "左(2)", "右左(1)}
  SIMPLE_EQUIP_TYPE: ["武器", "盾", "防装"],
  REGENERATE: {
    STAND: {
      HP: { INIT: 6, RATIO: 0.36 },
      MP: { INIT: 14, RATIO: 0.36 },
      ST: { INIT: 120, RATIO: 0.6 },
    },
    SIT: {
      HP: { INIT: 0, RATIO: 0 },
      MP: { INIT: 0, RATIO: 0 },
      ST: { INIT: 180, RATIO: 1.25 },
    },
  },
  STATUS_CAP: {
    HP: 1000,
    MP: 1000,
    ST: 1000,
    ATK: 500,
    HIT: 500,
    DEF: 500,
    AGI: 500,
    MAGIC: 500,
    耐火属性: 500,
    耐水属性: 500,
    耐風属性: 500,
    耐地属性: 500,
    耐無属性: 500,
    最大重量: 99999,
    ジャンプ: 99999,
    移動速度: 99999,
    泳ぎ速度: 99999,
    攻撃ディレイ: -60,
    魔法ディレイ: -60,
    クリティカル率: 100,
  },
  DEFAULT_TABLE_ROW_LIMIT: 30,
  EQUIP_TABLE_COLUMNS: [
    { className: "name", Header: "Name", accessor: "name", type: "string" },
    { className: "part", Header: "部位", accessor: "部位", type: "string" },
    { className: "skill", Header: "必要スキル", accessor: "必要スキル", type: "string" },
    { className: "hp", Header: "HP", accessor: "HP", type: "number" },
    { className: "mp", Header: "MP", accessor: "MP", type: "number" },
    { className: "st", Header: "ST", accessor: "ST", type: "number" },
    { className: "attack", Header: "攻撃力", accessor: "攻撃力", type: "number" },
    { className: "def", Header: "防御力", accessor: "防御力", type: "number" },
    { className: "hit", Header: "命中", accessor: "命中", type: "number" },
    { className: "agi", Header: "回避", accessor: "回避", type: "number" },
    { className: "magic", Header: "魔力", accessor: "魔力", type: "number" },
    { className: "fire_regist", Header: "耐火属性", accessor: "耐火属性", type: "number" },
    { className: "water_regist", Header: "耐水属性", accessor: "耐水属性", type: "number" },
    { className: "wind_regist", Header: "耐風属性", accessor: "耐風属性", type: "number" },
    { className: "earth_regist", Header: "耐地属性", accessor: "耐地属性", type: "number" },
    { className: "null_regist", Header: "耐無属性", accessor: "耐無属性", type: "number" },
    { className: "spec_delay", Header: "攻撃ディレイ", accessor: "攻撃ディレイ", type: "number" },
    { className: "magic_delay", Header: "魔法ディレイ", accessor: "魔法ディレイ", type: "number" },
    { className: "hp_reg", Header: "HP自然回復", accessor: "HP自然回復", type: "number" },
    { className: "mp_reg", Header: "MP自然回復", accessor: "MP自然回復", type: "number" },
    { className: "st_reg", Header: "ST自然回復", accessor: "ST自然回復", type: "number" },
    { className: "max_weight", Header: "最大重量", accessor: "最大重量", type: "number" },
    { className: "move_speed", Header: "移動速度", accessor: "移動速度", type: "number" },
    { className: "swim_speed", Header: "泳ぎ速度", accessor: "泳ぎ速度", type: "number" },
    { className: "spell_move_speed", Header: "詠唱移動速度", accessor: "詠唱移動速度", type: "number" },
    { className: "jump", Header: "ジャンプ力", accessor: "ジャンプ力", type: "number" },
    { className: "interval", Header: "攻撃間隔", accessor: "攻撃間隔", type: "number" },
    { className: "range", Header: "射程", accessor: "射程", type: "number" },
    // { className: "wind_regist", Header: "補正角", accessor: "補正角", type: "number" },
    { className: "special", Header: "特殊条件", accessor: "特殊条件", type: "string" },
  ],
  DEFAULT_EQUIP_TABLE_COLUMN_NAMES:[
    "name", 
    "part", 
    "skill", 
    "hp",  
    "mp",  
    "st",  
    "attack", 
    "def", 
    "hit", 
    "agi", 
    "magic", 
    "spe_delay", 
    "magic_delay",
    "hp_reg", 
    "mp_reg", 
    "st_reg", 
    "max_weight", 
    "move_speed", 
    "swim_speed", 
    "spell_move_sp",
    "jump", 
    "fire_regist",
    "water_regist",
    "wind_regist",
    "earth_regist",
    "null_regist"
  ],
  SKILL_CONVERT: {
    fist: "素手",
    sword: "刀剣",
    club: "こんぼう",
    spear: "槍",
    gun: "銃器",
    bow: "弓",
    shield: "盾",
    throw: "投げ",
    bite: "牙",
    trap: "罠",
    kick: "キック",
    battle: "戦闘技術",
    intoxication: "酩酊",
    mimicry: "物まね",
    training: "調教",
    ravage_spell: "破壊魔法",
    healing_spell: "回復魔法",
    protection_spell: "強化魔法",
    mystery_spell: "神秘魔法",
    summon_spell: "召喚魔法",
    death_spell: "死の魔法",
    magic_proficiency: "魔法熟練",
    natural_harmony: "自然調和",
    dark_command: "暗黒命令",
    transaction: "取引",
    shout: "シャウト",
    music: "音楽",
    steal: "盗み",
    gambling: "ギャンブル",
    paformance: "パフォーマンス",
    dance: "ダンス",
  },
  SKILLNAME_CONVERT_IMPORT: {
    筋力: "筋力",
    着こなし: "着こなし",
    攻撃回避: "回避",
    生命力: "生命",
    知能: "知能",
    持久力: "持久",
    精神力: "精神",
    集中力: "集中",
    呪文抵抗力: "抵抗",
    落下耐性: "落下",
    水泳: "水泳",
    死体回収: "死体",
    包帯: "包帯",
    自然回復: "自然回復",
    採掘: "採掘",
    伐採: "伐採",
    収穫: "収穫",
    釣り: "釣り",
    解読: "解読",
    料理: "料理",
    鍛冶: "鍛冶",
    醸造: "醸造",
    木工: "木工",
    裁縫: "裁縫",
    薬調合: "調合",
    装飾細工: "装飾",
    複製: "複製",
    栽培: "栽培",
    美容: "美容",
    素手: "素手",
    刀剣: "刀剣",
    こんぼう: "棍棒",
    槍: "槍",
    銃器: "銃",
    弓: "弓",
    盾: "盾",
    投げ: "投げ",
    牙: "牙",
    罠: "罠",
    キック: "キック",
    戦闘技術: "戦技",
    酩酊: "酩酊",
    物まね: "物まね",
    調教: "調教",
    破壊魔法: "破壊",
    回復魔法: "回復",
    強化魔法: "強化",
    神秘魔法: "神秘",
    召喚魔法: "召喚",
    死の魔法: "死魔",
    魔法熟練: "魔熟",
    自然調和: "調和",
    暗黒命令: "暗黒",
    取引: "取引",
    シャウト: "シャウト",
    音楽: "音楽",
    盗み: "盗み",
    ギャンブル: "ギャンブル",
    パフォーマンス: "パフォ",
    ダンス: "ダンス",
  },
  BUFF_DATA_TYPES: [
    "status_up",
    "regenerate",
    "delay",
    "reduce",
    "add_skill",
    "reactive",
    "other",
    "conversion",
    "skill_up",
    "increased",
    "vamp",
    "can_skill",
    "enchantment",
  ],

  ABBREVIATE_SKILL_NAME: {
    パフォーマンス: "パフォ",
    呪文抵抗力: "呪文抵抗",
  },
};

export default configs;
